spring.application.name=clinic

# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/clinic_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configurations
# A 256-bit (or larger) secure key for HS512 algorithm
app.jwt.secret=9a62bc6e-f14d-44a6-8095-263a0bf0c8194cf21d234a41d01ef6c0b38cbb5bb02e5b9be97405e326c9f6d4
app.jwt.expiration-ms=86400000
